spring:
  datasource:
    url: jdbc:mysql:///wordless
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
#    name: 不语文化
  jackson:
    date-format: "y-MM-dd HH:mm:ss"
    time-zone: GMT+8
  freemarker:
    request-context-attribute: request
server:
  servlet:
    context-path: /admin
    login-path: /login_w
#密码工具配置
password.salt: absuxn

#过滤器配置
filter:
  xss:
    exclude:
      #不过滤xss的接口，不带context-path，比如富文本编辑器
      paths: